config/routes.rb
Pcms::Application.routes.draw do

  scope 'amo', module: 'amo' do
    resources :job_orders do
      collection { get :new_import }
      collection { post :import }
    end

    resources :job_dates, only: [:index] do
      collection { get :be_schedule }
    end
  end

  get '/amo', to: redirect('/amo/job_dates')


  resources :films, except: [:new, :create] do
    member do
      post :split
      patch :restore
    end
    collection do
      get :edit_multiple
      patch :update_multiple
      get :formula_totals
      get :dimensions_map
      get :shelf_inventory
      get :solder_series
      get :qr_codes
    end
  end

  namespace :api, defaults: { format: 'json' } do
    post 'login', to: 'sessions#create'
    post 'logout', to: 'sessions#destroy'
    resources :films, only: [:show, :update], param: :serial do
      member do
        # using get for split for rack issue 676
        get :split
      end
      collection do
        patch :update_multiple
        get :assignable_orders
      end
    end
  end

  resources :master_films, except: [:show, :destroy] do
    collection do
      get :dimensions_map
      get :bvalue_series
      get :wep_series
    end
  end

  resources :sales_orders, except: [:show] do
    member do
      get :edit_ship_date
      patch :update_ship_date
      patch :move
    end
    collection do
      get :lead_time_histogram
      get :calendar
      get :product_type_totals
      get :assigned_formula_totals
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  scope module: "admin" do
    resources :users, except: :show
    resources :machines, except: :show
  end

  resources :film_movements, only: [:index] do
    collection do
      get :map
      get :inventory_totals
    end
  end

  resources :shipments, only: [:index] do
    collection do
      get :utilization_time_series
      get :shipped_area_time_series
    end
  end

  resources :productions, only: [:index] do
    collection do
      get :yield_time_series
      get :produced_area_time_series
      get :defects_time_series
    end
  end

  get 'planning/calendar', to: 'planning#calendar', as: :planning_calendar

  root to: 'films#index', phase: "lamination"
end

app/models/job_order.rb
class JobOrder < ActiveRecord::Base
  include Filterable

  has_many :job_dates, autosave: true, dependent: :destroy

  validates :serial, presence: true, uniqueness: true

  scope :serial_like, ->(serial) { where('serial ILIKE ?', serial.gsub('*', '%')) }
  scope :part_number_like, ->(part_number) { where('part_number ILIKE ?', part_number.gsub('*', '%')) }
  scope :run_number_like, ->(run_number) { where('run_number ILIKE ?', run_number.gsub('*', '%')) }
  scope :by_serial, -> { order('job_orders.serial DESC') }
  scope :text_search, ->(query) { reorder('').search(query) }

  include PgSearch
  pg_search_scope :search, 
    against: [:serial, :part_number, :quantity, :run_number, :note], 
    using: { tsearch: { prefix: true } }

  def set_job_dates(job_dates_attrs)
    job_dates_attrs.each do |job_date_attrs|
      job_date = job_dates.find_or_initialize_by(step: job_date_attrs[:step])
      job_date.job_order ||= self
      if job_date_attrs[:value].present?
        job_date.value = job_date_attrs[:value]
        job_date.completed = job_date_attrs[:completed]
        job_date.save!
      else
        job_date.destroy!
      end
    end
  end

  def date_of(step)
    if job_date = job_dates.find_by(step: step)
      job_date.value
    else
      ""
    end
  end

  def supermarket?
    !!(part_number =~ /^sm/i)
  end

  def rush?
    !!(priority =~ /rush/i)
  end

  def urgent?
    !!(priority =~ /urgent/i)
  end
end

app/controllers/amo/job_dates_controller.rb
class Amo::JobDatesController < AmoController
  http_basic_authenticate_with name: "avionics", password: "PI805"

  def index
    @month_grouped_job_dates = JobDate.order(:value).group_by { |jd| jd.value.beginning_of_month }
  end

  def be_schedule
    today = Time.zone.today
    four_week_be_dates = JobDate.where(value: today.beginning_of_week..(today + 28).end_of_week, step: "BE").order(value: :asc)
    @week_grouped_be_dates = four_week_be_dates.group_by do |job_date|
      job_date.value.beginning_of_week
    end

    render layout: 'application'
  end

  private

  def found_job_dates
    if any_searches?
      @found_job_dates ||= JobDate.filter(filtering_params)
    else
      @found_job_dates ||= []
    end
  end
  helper_method :found_job_dates

  def filtering_params
    params.slice(:text_search, :part_number_like)
  end
end

app/controllers/amo/job_orders_controller.rb
class Amo::JobOrdersController < AmoController
  require 'csv'

  http_basic_authenticate_with name: "james", password: "jamesonly"

  def index
    @job_orders = filtered_job_orders.page(params[:page])
  end

  def new
    @job_order = JobOrder.new
    @job_dates = JobDate::STEPS.map do |step|
      @job_order.job_dates.find_or_initialize_by(step: step)
    end
    render layout: false
  end

  def create
    @job_order = JobOrder.new(job_order_params)

    if @job_order.save
      @job_order.set_job_dates(params[:job_order][:job_dates].values)
    else
      render :display_modal_error_messages, locals: { object: @job_order }
    end
  end

  def edit
    session[:return_to] ||= request.referer
    @job_order = JobOrder.find(params[:id])
    @job_dates = JobDate::STEPS.map do |step|
      @job_order.job_dates.find_or_initialize_by(step: step)
    end
    render layout: false
  end

  def update
    @job_order = JobOrder.find(params[:id])
    @job_order.attributes = job_order_params

    if @job_order.save
      @job_order.set_job_dates(params[:job_order][:job_dates].values)
    else
      render :display_modal_error_messages, locals: { object: @job_order }
    end
  end

  def destroy
    @job_order = JobOrder.find(params[:id])
    @job_order.destroy!
    redirect_to session.delete(:return_to), notice: "Job Order #{@job_order.serial} deleted."
  end

  def new_import
  end

  def import
    csv_file = params[:job_orders_csv]

    if csv_file.nil? || File.extname(csv_file.original_filename) != ".csv"
      flash[:alert] = "Please choose a csv file."
    else
      JobOrder.destroy_all
      CSV.foreach(csv_file.path, headers: true) do |row|
        job_order_number = row["job_order_number"]
        if job_order_number.present?
          job_order = JobOrder.find_or_initialize_by(serial: job_order_number)
          job_order.part_number = row["part_number"] || ""
          job_order.run_number = row["run_number"] || ""
          job_order.quantity = row["quantity"] || ""
          job_order.priority = row["priority"] || ""

          job_order.save!

          JobDate::STEPS.each do |step|
            date_string = row[step]
            if date_string.present?
              job_date = job_order.job_dates.find_or_initialize_by(step: step)
              if completed_date_match = /\[(.*?)\]/.match(date_string)
                date_string = completed_date_match[0]
                job_date.completed = true
              end
              parsed_date = Date.strptime(date_string.strip, '%m/%d/%Y')
              job_date.value = parsed_date
              job_date.save!
            end
          end
        end
      end
      flash[:notice] = "Job orders imported"
    end

    redirect_to new_import_job_orders_path
  end

  private

  def job_order_params
    params.require(:job_order).permit(:serial, :part_number, :run_number, :quantity, :priority, :note)
  end

  def filtered_job_orders
    @filtered_job_orders ||= JobOrder
    .filter(filtering_params)
    .by_serial
  end
  helper_method :filtered_job_orders

  def filtering_params
    params.slice(:text_search, :serial_like, :run_number_like, :part_number_like)
  end
end

app/controllers/amo_controller.rb
class AmoController < ApplicationController
  skip_before_action :check_auth
  skip_before_action :check_ip
end

app/views/amo/job_orders/_job_order.html.erb
<tr id="<%= "joborder-#{job_order.id}" %>">
  <td class="actions">
    <%= link_to edit_job_order_path(job_order), { :"data-toggle" => "modal", :"data-target" => "#forms-modal", id: "job-order-#{job_order.id}-edit" } do %>
      <i class="fa fa-edit"></i>
    <% end %>
  </td>
  <td>
    <strong><%= job_order.serial %></strong>
  </td>
  <td>
    <%= job_order.quantity %>
  </td>
  <td>
    <%= job_order.part_number %>
  </td>
  <td>
    <%= job_order.run_number %>
  </td>
  <td>
    <%= job_order.priority %>
  </td>
  <td>
    <%= job_order.note %>
  </td>
  <% JobDate::STEPS.each do |step| %>
    <td>
      <% if job_date = job_order.job_dates.find_by(step: step) %>
        <%= job_date.value %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/amo/job_orders/_job_order_fields.html.erb
<%= f.text_field :serial, label: "Job Order #" %>
<%= f.text_field :part_number, label: "Part #" %>
<%= f.text_field :run_number, label: "Run #" %>
<%= f.text_field :quantity %>
<%= f.text_field :priority %>
<%= f.text_area :note %>

<hr>

<% @job_dates.each_with_index do |job_date, i| %>
  <fieldset>
    <%= f.fields_for "job_dates[#{i}]", job_date do |jdf| %>
      <%= render "shared/date_field", f: jdf, name: :value, label: jdf.object.step %>
      <div class="col-md-8 col-md-offset-2 checkbox">
        <label>
          <%= jdf.check_box :completed %>
        </label>
      </div>
      <%= jdf.hidden_field :step %>
    <% end %>
  </fieldset>
<% end %>

app/views/amo/job_orders/_search_form.html.erb
<%= render layout: 'shared/collapse_search_form', locals: { tab_param: :function, text_field: :text_search, show: any_searches? } do %>
  <div class="form-group">
    <%= label_tag :serial_like, "JO#", class: "control-label" %>
    <div class="col-md-12">
      <%= text_field_tag :serial_like, params[:serial_like], class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :part_number, "Part #", class: "control-label" %>
    <div class="col-md-12">
      <%= text_field_tag :part_number_like, params[:part_number_like], class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :run_number, "Run #", class: "control-label" %>
    <div class="col-md-12">
      <%= text_field_tag :run_number_like, params[:run_number_like], class: "form-control" %>
    </div>
  </div>
<% end %>

app/views/amo/job_orders/create.js.erb
$('#forms-modal').modal('hide')
$('.main #job-orders').prepend("<%= j render 'job_order', job_order: @job_order %>");
$("<%= "#joborder-#{@job_order.id}" %>").addClass("success")

app/views/amo/job_orders/edit.html.erb
<%= modal_form_for @job_order do |f| %>
  <div class="modal-header">
    <h4 class="modal-title text-center">Edit job order</h4>
  </div>
  <div class="modal-body">
    <%= render 'job_order_fields', f: f %>
  </div>
  <div class="modal-footer">
    <%= link_to "Delete", @job_order, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger pull-left" %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= f.submit "Update job order", class: "btn btn-success", data: { disable_with: "Submitting..." } %>
  </div>
<% end %>

app/views/amo/job_orders/index.html.erb
<%= paginate @job_orders %>

<%= link_to_modal_new(new_job_order_path, "Enter job order") %>

<table id="job-orders" class="table table-condensed">
  <thead>
    <tr>
      <th></th>
      <th>JO#</th>
      <th>Qty</th>
      <th>Part #</th>
      <th>Run #</th>
      <th>Priority</th>
      <th>Note</th>
      <% JobDate::STEPS.each do |step| %>
        <th>
          <%= step %>
        </th>
      <% end %>
    </tr>
  </thead>
  <%= render partial: "job_order", collection: @job_orders %>
</table>

app/views/amo/job_orders/new.html.erb
<%= modal_form_for @job_order do |f| %>
  <div class="modal-header">
    <h4 class="modal-title text-center">Enter job order</h4>
  </div>
  <div class="modal-body">
    <%= render 'job_order_fields', f: f %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= f.submit "Add job order", class: "btn btn-success", data: { disable_with: "Submitting..." } %>
  </div>
<% end %>

app/views/amo/job_orders/new_import.html.erb
<div class="row">
  <div class="col-md-4">
    <h3>Import job orders from CSV</h3>
    <%= form_tag import_job_orders_path, multipart: true do %>
      <div class="form-group">
        <%= file_field_tag :job_orders_csv %>
      </div>
      <%= submit_tag "Import", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/amo/job_orders/update.js.erb
$('#forms-modal').modal('hide')
var job_order_row = $("<%= "#joborder-#{@job_order.id}" %>")
$(job_order_row).replaceWith("<%= j render 'job_order', job_order: @job_order %>");
$(job_order_row.selector).addClass("info")