config/routes.rb
Pcms::Application.routes.draw do

  scope 'amo', module: 'amo' do
    resources :job_orders do
      collection { get :new_import }
      collection { post :import }
    end

    resources :job_dates, only: [:index] do
      collection { get :be_schedule }
    end
  end

  get '/amo', to: redirect('/amo/job_dates')


  resources :films, except: [:new, :create] do
    member do
      post :split
      patch :restore
    end
    collection do
      get :edit_multiple
      patch :update_multiple
      get :formula_totals
      get :dimensions_map
      get :shelf_inventory
      get :solder_series
      get :qr_codes
    end
  end

  namespace :api, defaults: { format: 'json' } do
    post 'login', to: 'sessions#create'
    post 'logout', to: 'sessions#destroy'
    resources :films, only: [:show, :update], param: :serial do
      member do
        # using get for split for rack issue 676
        get :split
      end
      collection do
        patch :update_multiple
        get :assignable_orders
      end
    end
  end

  resources :master_films, except: [:show, :destroy] do
    collection do
      get :dimensions_map
      get :bvalue_series
      get :wep_series
    end
  end

  resources :sales_orders, except: [:show] do
    member do
      get :edit_ship_date
      patch :update_ship_date
      patch :move
    end
    collection do
      get :lead_time_histogram
      get :calendar
      get :product_type_totals
      get :assigned_formula_totals
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  scope module: "admin" do
    resources :users, except: :show
    resources :machines, except: :show
  end

  resources :film_movements, only: [:index] do
    collection do
      get :map
      get :inventory_totals
    end
  end

  resources :shipments, only: [:index] do
    collection do
      get :utilization_time_series
      get :shipped_area_time_series
    end
  end

  resources :productions, only: [:index] do
    collection do
      get :yield_time_series
      get :produced_area_time_series
      get :defects_time_series
    end
  end

  get 'planning/calendar', to: 'planning#calendar', as: :planning_calendar

  root to: 'films#index', phase: "lamination"
end

app/models/master_film.rb
class MasterFilm < ActiveRecord::Base
  include Filterable
  include Tenancy

    DEFECT_TYPES = ['Air Bubble', 'BBL', 'Bend', 'Blocker Mark', 'Blotchy', 'Brown Line', 'BWS', 'Clear Area', 'Clear Edges', 'Clear Peak', 'Clear Spot', 'Clear Wavy Area', 'Dent', 'Dimball', 'Dimples', 'Dropper Mark', 'Delamination', 'Dust/Dirt/FOD', 'Edge Delam', 'Foamy Streak', 'Glue Impression', 'Knot', 'Material Traces', 'MD Line', 'Non-Uniform', 'Pickle', 'Peak', 'Repeating Defect', 'ROM', 'Scratch', 'Short', 'Small Clear', 'Spacer Cluster', 'Spacer Spot', 'Streak', 'Thick Spot', 'Thick Material', 'Transverse Line', 'Wavy', 'White Spot']

  enum function: [ :production, :test, :transfer ]

  has_many :films, dependent: :destroy
  belongs_to :machine

  before_validation :upcase_attributes, :set_serial_date
  before_save :set_yield
  after_update :update_film_serials, if: Proc.new { |mf| mf.serial_changed? }

  delegate :code, to: :machine, prefix: true, allow_nil: true
  alias_attribute :width, :effective_width
  alias_attribute :length, :effective_length

  validates :serial, presence: true, 
                     uniqueness: { case_sensitive: false, scope: :tenant_code },
                     format: { with: /\A[A-Z]\d{4}-\d{2}\z/ }
  validates :effective_width, numericality: { greater_than_or_equal_to: 0 }
  validates :effective_length, numericality: { greater_than_or_equal_to: :effective_width }

  scope :active, -> { all.joins(:films).merge(Film.not_deleted).uniq }
  scope :function, ->(function) { where(function: functions[function]) }
  scope :function_not, ->(function) { where("function <> ?", MasterFilm.functions[function]) }
  scope :serial_date_before, ->(date) { where('master_films.serial_date <= ?', date) }
  scope :serial_date_after, ->(date) { where('master_films.serial_date >= ?', date) }
  scope :by_serial, -> { order('master_films.serial DESC') }
  scope :formula_like, ->(formula) { where('formula ILIKE ?', formula.gsub('*', '%')) }
  scope :text_search, ->(query) { reorder('').search(query) }
  
  include PgSearch
  pg_search_scope :search, 
    against: [:serial, :formula, :film_code_top, :thinky_code, :operator, :chemist, :inspector, :defects, :note],
    using: { tsearch: { prefix: true } },
    associated_against: { machine: [:code] }

  def save_and_create_child(actor)
    if save
      film = create_film(:lamination)
      film.record_movement("raw", "lamination", actor)
    end
  end

  def create_film(phase, width = 0, length = 0)
    film = films.create!(serial: "#{serial}-#{next_division}", 
                         tenant_code: tenant_code, 
                         phase: phase)
    film.create_dimension(width, length)
    film.set_area
    film
  end

  def update_film_serials
    films.each do |f|
      div = f.serial[8..-1]
      f.update_columns(serial: serial + div)
    end
  end

  def effective_area
    effective_width*effective_length/tenant.area_divisor
  end

  def defect_count(type)
    defects[type].to_i
  end

  def self.defect_occurrences
    ary = defect_types.map do |t|
      [t, select { |mf| mf.defects[t] }.count]
    end
    Hash[ary]
  end

  def defects_sum
    defects.values.map(&:to_i).sum
  end

  def self.defect_types
    types = all.inject([]) do |arry, mf|
      arry + mf.defects.keys
    end
    types.uniq
  end

  def next_division
    films.pluck(:serial).map { |s| s[/.+-.+-(\d+)/, 1].to_i }.max.to_i + 1
  end

  def self.total_effective_area
    all.map{ |mf| mf.effective_area }.sum
  end

  def self.avg_yield
    return nil if count == 0
    (all.map { |mf| mf.yield.to_f }.sum)/count
  end

  def self.to_csv(options = {})
    types = defect_types
    CSV.generate(options) do |csv|
      csv << %w(Serial Formula Mix/g Machine ITO Thinky b* Chemist Operator Inspector EffW EffL) + types
      all.each do |mf|
        csv << [mf.serial, mf.formula, mf.mix_mass, mf.machine_code, mf.film_code_top, mf.thinky_code, mf.b_value, mf.chemist, mf.operator, mf.inspector, mf.effective_width, mf.effective_length, mf.yield] + types.map{ |type| mf.defect_count(type) }
      end
    end
  end

  private

  def set_serial_date
    year = serial[0].ord + 1943
    month = serial[1,2].to_i
    day = serial[3,2].to_i
    self.serial_date = Date.new(year, month, day)
  rescue ArgumentError, NoMethodError
    self.errors[:serial] = "does not correspond to a valid date"
  end
  
  def upcase_attributes
    formula.upcase! if formula.present?
    film_code_top.upcase! if film_code_top.present?
    thinky_code.upcase! if thinky_code.present?
    serial.upcase! if serial.present?
  end

  def set_yield
    if yieldable?
      self.yield = 100*tenant.yield_multiplier*(effective_area/mix_mass)/machine.yield_constant
    else
      self.yield = nil
    end
  end

  def yieldable?
    mix_mass && machine
  end
end

app/controllers/api/films_controller.rb
module Api
  class FilmsController < ApiController

    def show
      @film = tenant_films.find_by_serial!(params[:serial])
    rescue ActiveRecord::RecordNotFound
      render text: "Film does not exist.", status: 404
    end

    def update
      @film = tenant_films.find_by_serial!(params[:serial])
      unless @film.update_and_move(film_params, params[:destination], current_user)
        render json: @film.errors.full_messages.to_json, status: 500
      end
    end

    def split
      film = tenant_films.find_by_serial!(params[:serial])
      @split = film.split
    rescue ActiveRecord::RecordNotFound
      render text: "Film does not exist.", status: 404
    end

    def update_multiple
      @films = tenant_films.where(serial: params[:film_serials])
      @films.each do |film|
        film.update_and_move(update_multiple_films_params, params[:destination], current_user)
      end
      render json: @films.to_json
    end

    def assignable_orders
      @in_progress_orders = current_tenant.sales_orders.in_progress
    end

    private

    def film_params
      params.permit(:note, :shelf, :sales_order_id, :order_fill_count, dimensions_attributes: [:width, :length, :_destroy, :id])
    end

    def update_multiple_films_params
      params.reject { |k,v| v.blank? }.permit(:shelf)
    end

    def tenant_films
      @tenant_films ||= current_tenant.films
    end
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  require 'rqrcode'

  def index
    @films = filtered_films.order_by(sort[0], sort[1]).page(params[:page])
    respond_to do |format|
      format.html
      format.csv { render csv: filtered_films }
    end
  end

  def formula_totals
    @data = FilmFormulaTotals.new(filtered_films)
  end

  def dimensions_map
    @data = DimensionsMap.new(filtered_films)
  end

  def shelf_inventory
    @shelves = filtered_films.has_shelf.group_by(&:shelf).sort_by { |k,v| k }
  end

  def solder_series
    @data = SolderSeries.new(filtered_films)
  end

  def edit
    session[:return_to] ||= request.referer
    @film = tenant_films.find(params[:id])
    render layout: false
  end

  def update
    @film = tenant_films.find(params[:id])
    unless @film.update_and_move(film_params, params[:destination], current_user)
      render :display_modal_error_messages, locals: { object: @film }
    end
  end 

  def edit_multiple
    @films = tenant_films.find(params[:film_ids])
    if params[:edit]
      render :edit_multiple, layout: false
    elsif params[:qrcodes]
      render :qr_codes, layout: false
    end
  end

  def update_multiple
    @films = tenant_films.find(params[:film_ids])
    @films.each do |film|
      film.update_and_move(update_multiple_films_params, params[:destination], current_user)
    end
  end

  def split
    @film = tenant_films.find(params[:id])
    @split = @film.split
  end

  def destroy
    @film = tenant_films.find(params[:id])
    @film.update_attributes(deleted: true)
    redirect_to session.delete(:return_to), notice: "Film #{@film.serial} deleted."
  end

  def restore
    @film = tenant_films.find(params[:id])
    @film.update_attributes(deleted: false)
  end

  private

  def tenant_films
    @tenant_films ||= current_tenant.films
  end
  helper_method :tenant_films

  def filtered_films
    @filtered_films ||= tenant_films.join_dimensions
                                    .phase(params[:phase], current_tenant)
                                    .filter(filtering_params)
  end
  helper_method :filtered_films

  def dimensions_searched?
    params[:width_greater_than].present? || params[:length_greater_than].present?
  end

  def sort
    params.fetch(:sort) do
      dimensions_searched? ? 'area-asc' : 'serial-desc'
    end.split('-')
  end
  helper_method :sort

  def filtering_params
    params.slice(:text_search, :formula_like, :width_greater_than, :length_greater_than, :serial_date_before, :serial_date_after)
  end

  def film_params
    params.require(:film).permit(:note, :shelf, :sales_order_id, :order_fill_count,
                                 dimensions_attributes: [:width, :length, :_destroy, :id],
                                 solder_measurements_attributes: [:height1, :height2, :_destroy, :id])
  end

  def update_multiple_films_params
    params.require(:film).reject { |k,v| v.blank? }.permit(:shelf, :sales_order_id)
  end
end

app/helpers/films_helper.rb
module FilmsHelper
  def utilization_label(width, length)
    if params[:width_greater_than].present? && params[:length_greater_than].present? && width >= search_width && length >= search_length
      content_tag(:span, class: "label label-warning") do
        format_utilization(100*(search_width*search_length)/(width*length))
      end
    end
  end

  def sales_order_assign_choices(film)
    in_progress_orders = current_tenant.sales_orders.in_progress
    film.sales_order.present? ? in_progress_orders.to_set << film.sales_order : in_progress_orders
  end

  def destination_choices(films)
    films.map{ |f| f.valid_destinations }.uniq.reduce(:&)
  end

  def search_width
    @search_width ||= params[:width_greater_than].to_f unless params[:width_greater_than].empty?
  end

  def search_length
    @search_length ||= params[:length_greater_than].to_f unless params[:length_greater_than].empty?
  end
end

app/views/films/_film.html.erb
<tr id="<%= "film-#{film.id}" %>" class="film">
  <td class="select-box">
    <%= check_box_tag "film_ids[]", film.id, false, class: "film-select" unless film.deleted? %>
  </td>
  <td class="actions">
    <% if film.deleted == true %>
      <%= link_to restore_film_path(film), method: :patch, remote: true, id: "film-#{film.id}-restore" do %>
        <i class="fa fa-wrench"></i>
      <% end %>
    <% else %>
      <%= link_to edit_film_path(film), { :"data-toggle" => "modal", :"data-target" => "#forms-modal", id: "film-#{film.id}-edit" } do %>
        <i class="fa fa-edit"></i>
      <% end %>
      <% if %w(stock reserved).include? film.phase %>
        <%= link_to split_film_path(film), method: :post, remote: true, id: "film-#{film.id}-split", data: { confirm: "Are you sure?" } do %>
          <i class="fa fa-scissors"></i>
        <% end %>
      <% end %>
    <% end %>
  </td>
  <td class="serial">
    <strong><%= film.serial %></strong> <span class="label label-default"><%= film.formula %></span>
  </td>
  <td class="width">
    <% film.dimensions.each do |d| %>
      <%= "#{d.width}#{tag('br')}".html_safe %>
    <% end %>
  </td>
  <td class="length">
    <% film.dimensions.each do |d| %>
      <%= "#{d.length}#{tag('br')}".html_safe %>
    <% end %>
  </td>
  <td class="area">
    <% film.dimensions.each do |d| %>
      <%= "#{format_area(d.area)}#{utilization_label(d.width, d.length)}#{tag('br')}".html_safe %>
    <% end %>
  </td>
  <td class="shelf"><%= film.shelf %></td>
  <td class="order">
    <%= film.sales_order_code %>
    <% if film.order_fill_count > 1 && film.sales_order.present? %>
      <span class="badge"><%= film.order_fill_count %></span>
    <% end %>
  </td>
  <td class="b_value">
    <%= film.b_value %>
  </td>
  <td class="note"><%= film.note %></td>
  <td class="serial_date"><%= film.serial_date %></td>
</tr>

app/views/films/_film_fields.html.erb
<%= f.fields_for :dimensions do |df| %>
  <%= render 'dimension_fields', f: df %>
<% end %>
<div class="add-fields-link-wrapper form-group">
  <div class="col-md-offset-2 col-md-8">
    <%= link_to_add_fields "Add dimensions", f, :dimensions %>
  </div>
</div>
<%= f.text_field :shelf %>
<div class="form-group">
  <%= f.label :sales_order_id, "SO", class: "control-label col-md-2" %>
  <div class="col-md-5">
    <%= f.collection_select :sales_order_id, sales_order_assign_choices(film), :id, :code, { include_blank: "---" }, class: "form-control", default: true %>
  </div>
  <div class="col-md-3">
    <%= f.number_field :order_fill_count, placeholder: "Count", class: "form-control", default: true %>
  </div>
</div>
<%= f.fields_for :solder_measurements do |smf| %>
  <%= render 'solder_measurement_fields', f: smf %>
<% end %>
<div class="add-fields-link-wrapper form-group">
  <div class="col-md-offset-2 col-md-8">
    <%= link_to_add_fields "Add solder measurement", f, :solder_measurements %>
  </div>
</div>
<%= f.text_area :note %>
<div class="form-group">
  <div class="col-md-offset-2 col-md-8">
    <%= select_tag :destination, options_for_select(destination_choices([film])), { prompt: "Move to...", class: "form-control" } %>
  </div>
</div>

app/views/films/_moved_film.html.erb
<tr id="<%= "film-#{film.id}" %>" class="alert alert-info">
  <td></td>
  <td></td>
  <td colspan="100%">
    <%= "#{content_tag(:strong, film.serial)} #{content_tag(:i, nil, class: 'fa fa-arrow-right')} #{content_tag(:strong, film.phase)}".html_safe %>
  </td>
</tr>

app/views/films/_solder_measurement_fields.html.erb
<fieldset class="form-group solder-height-fields">
  <%= label_tag "Solder heights", nil, class: "control-label col-md-2" %>
  <div class="col-md-4">
    <%= f.number_field :height1, placeholder: "Height 1", step: "any", default: true %>
  </div>
  <div class="col-md-4">
    <%= f.number_field :height2, placeholder: "Height 2", step: "any", default: true %>
  </div>
  <%= f.hidden_field :_destroy %>
  <%= link_to '#', class: "remove-fields" do %>
    <i class="fa fa-minus"></i>remove
  <% end %>
</fieldset>

app/views/films/dimensions_map.html.erb
<script>
  $(function () { 
    $('#dimensions-map').highcharts({
      chart: {
        type: 'heatmap',
        height: 600
      },

      title: {
        text: false
      },

      xAxis: {
        categories: <%= raw @data.x_axis_categories %>,
        gridLineWidth: 2,
        title: {
          text: "Length"
        }
      },

      yAxis: {
        categories: <%= raw @data.y_axis_categories %>,
        gridLineWidth: 2,
        title: {
          text: "Width"
        }
      },

      colorAxis: {
        min: 0,
        minColor: '#FFFFFF',
        maxColor: Highcharts.getOptions().colors[0]
      },

      legend: {
        align: 'right',
        layout: 'vertical',
        margin: 0,
        verticalAlign: 'top',
        y: 25,
        symbolHeight: 320
      },

      tooltip: {
        formatter: function () {
          var serial_array = this.point.serials;
          var serial_str = ""; 
          for(var i = 0; i < serial_array.length; i++){
            serial_str = serial_str + serial_array[i] + '<br>';
          }
          return serial_str;
        }
      },

      series: [{
        borderWidth: 1,
        data: [ 
        <% @data.map_hash.each do |p| %>
        { 
          x: <%= p[:coords][0] %>,
          y: <%= p[:coords][1] %>,
          value: <%= p[:value] %>,
          serials: <%= raw p[:serials] %>
        },
        <% end %>
        ],
       
        dataLabels: {
          enabled: true,
          color: 'black',
          style: {
            textShadow: 'none'
          }
        }
      }]
    });
  });
</script>

<div id="dimensions-map" class="chart"></div>

app/views/films/edit.html.erb
<%= modal_form_for @film do |f| %>
  <div class="modal-header">
    <h4 class="modal-title text-center"><%= @film.serial %></h4>
  </div>
  <div class="modal-body">
    <%= render 'film_fields', f: f, film: @film %>
  </div>
  <div class="modal-footer">
    <%= link_to_delete_if_admin(@film) %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= f.submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

app/views/films/edit_multiple.html.erb
<%= modal_form_for :film, url: update_multiple_films_path, method: :patch do |f| %>
  <div class="modal-header">
    <ul class="list-inline">
      <% @films.each do |film| %>
        <li>
        <%= hidden_field_tag "film_ids[]", film.id %>
        <h4><%= film.serial %></h4>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="modal-body">
    <%= f.text_field :shelf, class: "form-control" %>
    <%= f.collection_select :sales_order_id, current_tenant.sales_orders.in_progress, :id, :code, { include_blank: true }, class: "form-control" %>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-8">
        <%= select_tag :destination, options_for_select(destination_choices(@films)), { prompt: "Move to...", class: "form-control" } %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= submit_tag "Move all", class: "btn btn-success" %>
  </div>
<% end %>

app/views/films/formula_totals.html.erb
<script>
  $(function () { 
    $('#film-formula-totals').highcharts({
      chart: {
        type: 'bar'
      },
      title: {
        text: false
      },
      xAxis: {
        categories: <%= raw(@data.values) %>
      },
      yAxis: [{
        title: {
          text: 'Count'
        }
      }, {
        title: {
          text: 'Area'
        }
      }],
      plotOptions: {
        series: {
          groupPadding: 0.25
        }
      },
      series: [{
        yAxis: 0,
        name: 'Count',
        data: <%= raw(@data.counts) %>,
        pointPlacement: 0.2
        }, {
        yAxis: 1,
        name: 'Area',
        data: <%= raw(@data.areas) %>,
        pointPlacement: -0.2
      }]
    });
  });
</script>

<div id="film-formula-totals" class="chart"></div>

app/views/films/qr_codes.html.erb
<div class="modal-body" id="qr-container">
  <div id="qr-codes">
  <% @films.each do |f| %>
  <div class="qr-code text-center">
  <table>
    <% f.qr_code.modules.each_index do |x| %>
      <tr>  
      <% f.qr_code.modules.each_index do |y| %>
        <% if f.qr_code.dark?(x,y) %>
          <td class="black"/>
        <% else %>
          <td class="white"/>
        <% end %>
      <% end %>
      </tr>
    <% end %>
  </table>
  <%= f.serial %>
  </div>
  <% end %>
  </div>
</div>
<div class="modal-footer">
  <%= link_to("Print", "#", id: "print-qr", class: "btn btn-default") %>
</div>

app/views/films/shelf_inventory.html.erb
<div class="panel-group">
  <% @shelves.each do |s| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" href="<%= "#collapse-#{s[0].parameterize}" %>">
            <%= "#{s[0]} " %><span class="badge"><%= s[1].count %></span>
          </a>
        </h4>
      </div>
      <ul id="<%= "collapse-#{s[0].parameterize}" %>" class="list-group panel-collapse collapse">
        <% s[1].each do |f| %>
          <li class="list-group-item">
          <strong><%= "#{f.serial} --" %></strong><%= " #{f.width} x #{f.length}" %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/films/solder_series.html.erb
<div class="pull-right">
  <dl class="dl-horizontal">
    <dt>mean</dt>
    <dd><%= number_with_precision(@data.mean, precision: 5) %></dd>
    <dt>3 sigma</dt>
    <dd><%= number_with_precision(@data.three_sigma, precision: 5) %></dd>
    <dt>CpK</dt>
    <dd><%= number_with_precision(@data.cpk, precision: 5) %></dd>
  </dl>
</div>

<script>
  $(function () {
    $('#solder-series').highcharts({
      chart: {
        type: 'scatter'
      },
      title: {
        text: false
      },
      tooltip:{
        formatter:function(){
          return 'serial: <strong>' + this.key + '</strong><br />height: <strong>' + this.y + '</strong>';
        }
      },
      xAxis: {
        title: {
          text: 'Serial'
        },
        categories: <%= raw @data.categories %>,
        labels: {
          step: 20,
          rotation: -70
        }
      },
      yAxis: {
        min: 0,
        title: {
          text: 'solder height'
        },
        plotLines: [{
          color: 'red',
          value: 0.043,
          width: 2,
          zIndex: 5,
          label: {
            align: 'right',
            text: 'Max'
          }
        }]
      },
      series: [{
        name: 'height 1',
        data: <%= @data.data[:height1].to_json.html_safe %>,
      },{
        name: 'height 2',
        data: <%= @data.data[:height2].to_json.html_safe %>,
      }]
    });
  });
</script>
<div id="solder-series" class="chart"></div>

app/views/films/split.js.erb
$("<%= "#film-#{@film.id}" %>").after("<%= j render 'film', film: @split %>");
$("<%= "#film-#{@split.id}" %>").addClass("success");

app/views/films/unassign.js.erb
$("<%= "#film-#{@film.id}-label" %>").html("<%= "#{@film.serial}" %>").attr("class", "label label-default");

app/views/films/update.js.erb
$('#forms-modal').modal('hide')
var film_row = $("<%= "#film-#{@film.id}" %>")
<% if @film.previous_changes.keys.include?("phase") %>
  film_row.replaceWith("<%= j render 'moved_film', film: @film %>");
<% else %>
  film_row.replaceWith("<%= j render 'film', film: @film %>");
  $(film_row.selector).addClass("info")
<% end %>