config/routes.rb
Pcms::Application.routes.draw do

  scope 'amo', module: 'amo' do
    resources :job_orders do
      collection { get :new_import }
      collection { post :import }
    end

    resources :job_dates, only: [:index] do
      collection { get :be_schedule }
    end
  end

  get '/amo', to: redirect('/amo/job_dates')


  resources :films, except: [:new, :create] do
    member do
      post :split
      patch :restore
    end
    collection do
      get :edit_multiple
      patch :update_multiple
      get :formula_totals
      get :dimensions_map
      get :shelf_inventory
      get :solder_series
      get :qr_codes
    end
  end

  namespace :api, defaults: { format: 'json' } do
    post 'login', to: 'sessions#create'
    post 'logout', to: 'sessions#destroy'
    resources :films, only: [:show, :update], param: :serial do
      member do
        # using get for split for rack issue 676
        get :split
      end
      collection do
        patch :update_multiple
        get :assignable_orders
      end
    end
  end

  resources :master_films, except: [:show, :destroy] do
    collection do
      get :dimensions_map
      get :bvalue_series
      get :wep_series
    end
  end

  resources :sales_orders, except: [:show] do
    member do
      get :edit_ship_date
      patch :update_ship_date
      patch :move
    end
    collection do
      get :lead_time_histogram
      get :calendar
      get :product_type_totals
      get :assigned_formula_totals
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  scope module: "admin" do
    resources :users, except: :show
    resources :machines, except: :show
  end

  resources :film_movements, only: [:index] do
    collection do
      get :map
      get :inventory_totals
    end
  end

  resources :shipments, only: [:index] do
    collection do
      get :utilization_time_series
      get :shipped_area_time_series
    end
  end

  resources :productions, only: [:index] do
    collection do
      get :yield_time_series
      get :produced_area_time_series
      get :defects_time_series
    end
  end

  get 'planning/calendar', to: 'planning#calendar', as: :planning_calendar

  root to: 'films#index', phase: "lamination"
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tenancy

  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :full_name, presence: true, uniqueness: { case_sensitive: false }

  scope :chemists, -> { where(chemist: true) }
  scope :operators, -> { where(operator: true) }
  scope :inspectors, -> { where(inspector: true) }

  enum role_level: [ :user, :admin ]

  def self.names
    pluck(:full_name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = users.page(params[:page])
  end

  def new
    @user = current_tenant.new_user
    render layout: false
  end

  def create
    @user = current_tenant.new_user(user_params)
    unless @user.save
      render :display_modal_error_messages, locals: { object: @user }
    end
  end

  def edit
    session[:return_to] ||= request.referer
    @user = users.find(params[:id])
    render layout: false
  end

  def update
    @user = users.find(params[:id])
    unless @user.update(user_params)
      render :display_modal_error_messages, locals: { object: @user }
    end
  end 

  def destroy
    @user = users.find(params[:id])
    @user.destroy!
    redirect_to session.delete(:return_to), notice: "User #{@user.full_name} deleted."
  end

  private

  def users
    current_tenant.users
  end

  def user_params
    params.require(:user).permit(:username, :full_name, :password, :password_confirmation, :chemist, :operator, :role_level, :inspector)
  end
end

app/views/admin/users/_user.html.erb
<tr id="<%= "user-#{user.id}" %>">
  <td>
    <%= link_to_modal_edit(edit_user_path(user), user, class: "edit-user") %>
  </td>
  <td class="full_name"><%= user.full_name %></td>
  <td class="username"><%= user.username %></td>
  <td class="role_title"><%= user.role_level %></td>
  <td class="chemist"><%= user.chemist %></td>
  <td class="operator"><%= user.operator %></td>
  <td class="inspector"><%= user.inspector %></td>
</tr>

app/views/admin/users/create.js.erb
$('#forms-modal').modal('hide')
$('.main tbody').prepend("<%= j render 'user', user: @user %>");
$("<%= "#user-#{@user.id}" %>").addClass("success")

app/views/admin/users/edit.html.erb
<%= modal_form_for @user do |f| %>
  <div class="modal-header">
    <h4 class="modal-title text-center"><%= @user.full_name %></h4>
  </div>
  <div class="modal-body">
    <%= f.text_field :username %>
    <%= f.select :role_level, User.role_levels.keys, {}, label: "Role" %>
    <div class="col-md-offset-2 col-md-10">
      <strong><%= link_to "change password", "#", class: "show-password-fields" %></strong>
    </div>
    <div class="password-fields">
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.check_box :chemist %>
    <%= f.check_box :operator %>
    <%= f.check_box :inspector %>
  </div>
  <div class="modal-footer">
    <%= link_to_delete_if_admin(@user) %>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= f.submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<%= paginate @users %>

<%= link_to_modal_new(new_user_path, "New user") %>

<table class="table table-condensed table-hover">
  <thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Username</th>
    <th>Role</th>
    <th>Chemist</th>
    <th>Operator</th>
    <th>Inspector</th>
  </tr>
  <tr>
  </tr>
  </thead>
  <tbody>
  <%= render @users %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= modal_form_for @user do |f| %>
  <div class="modal-header">
    <h4 class="modal-title text-center">New user</h4>
  </div>
  <div class="modal-body">
    <%= f.text_field :full_name %>
    <%= f.text_field :username %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <%= f.select :role_level, User.role_levels.keys, {}, label: "Role" %>
    <%= f.check_box :chemist %>
    <%= f.check_box :operator %>
    <%= f.check_box :inspector %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= f.submit "Create user", class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/users/update.js.erb
var user_row = $("<%= "#user-#{@user.id}" %>")
$('#forms-modal').modal('hide')
user_row.replaceWith("<%= j render 'user', user: @user %>");
$(user_row.selector).addClass("info");