config/routes.rb
Pcms::Application.routes.draw do

  scope 'amo', module: 'amo' do
    resources :job_orders do
      collection { get :new_import }
      collection { post :import }
    end

    resources :job_dates, only: [:index] do
      collection { get :be_schedule }
    end
  end

  get '/amo', to: redirect('/amo/job_dates')


  resources :films, except: [:new, :create] do
    member do
      post :split
      patch :restore
    end
    collection do
      get :edit_multiple
      patch :update_multiple
      get :formula_totals
      get :dimensions_map
      get :shelf_inventory
      get :solder_series
      get :qr_codes
    end
  end

  namespace :api, defaults: { format: 'json' } do
    post 'login', to: 'sessions#create'
    post 'logout', to: 'sessions#destroy'
    resources :films, only: [:show, :update], param: :serial do
      member do
        # using get for split for rack issue 676
        get :split
      end
      collection do
        patch :update_multiple
        get :assignable_orders
      end
    end
  end

  resources :master_films, except: [:show, :destroy] do
    collection do
      get :dimensions_map
      get :bvalue_series
      get :wep_series
    end
  end

  resources :sales_orders, except: [:show] do
    member do
      get :edit_ship_date
      patch :update_ship_date
      patch :move
    end
    collection do
      get :lead_time_histogram
      get :calendar
      get :product_type_totals
      get :assigned_formula_totals
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  scope module: "admin" do
    resources :users, except: :show
    resources :machines, except: :show
  end

  resources :film_movements, only: [:index] do
    collection do
      get :map
      get :inventory_totals
    end
  end

  resources :shipments, only: [:index] do
    collection do
      get :utilization_time_series
      get :shipped_area_time_series
    end
  end

  resources :productions, only: [:index] do
    collection do
      get :yield_time_series
      get :produced_area_time_series
      get :defects_time_series
    end
  end

  get 'planning/calendar', to: 'planning#calendar', as: :planning_calendar

  root to: 'films#index', phase: "lamination"
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  include Tenancy

  validates :code, presence: true
  validates :yield_constant, presence: true
end

app/controllers/admin/machines_controller.rb
class Admin::MachinesController < AdminController
  def index
    @machines = machines.page(params[:page])
  end

  def new
    @machine = current_tenant.new_machine
    render layout: false
  end

  def create
    @machine = current_tenant.new_machine(machine_params)
    unless @machine.save
      render :display_modal_error_messages, locals: { object: @machine }
    end
  end

  def edit
    session[:return_to] ||= request.referer
    @machine = machines.find(params[:id])
    render layout: false
  end

  def update
    @machine = machines.find(params[:id])
    unless @machine.update(machine_params)
      render :display_modal_error_messages, locals: { object: @machine }
    end
  end 

  private

  def machines
    current_tenant.machines
  end

  def machine_params
    params.require(:machine).permit(:code, :yield_constant)
  end
end

app/views/admin/machines/_machine.html.erb
<tr id="<%= "machine-#{machine.id}" %>">
  <td>
    <%= link_to_modal_edit(edit_machine_path(machine), machine, class: "edit-machine") %>
  </td>
  <td class="code"><%= machine.code %></td>
  <td class="yield_constant"><%= machine.yield_constant %></td>
</tr>

app/views/admin/machines/_machine_fields.html.erb
<%= f.text_field :code %>
<%= f.number_field :yield_constant, label: "Yield const", step: "any" %>

app/views/admin/machines/create.js.erb
$('#forms-modal').modal('hide')
$('.main tbody').prepend("<%= j render 'machine', machine: @machine %>");
$("<%= "#machine-#{@machine.id}" %>").addClass("success")

app/views/admin/machines/edit.html.erb
<%= modal_form_for @machine do |f| %>
  <div class="modal-body">
    <%= render 'machine_fields', f: f %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= f.submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/machines/index.html.erb
<%= paginate @machines %>

<%= link_to_modal_new(new_machine_path, "New machine") %>

<table class="table table-condensed table-hover">
  <thead>
  <tr>
    <th></th>
    <th>Code</th>
    <th>Yield constant</th>
  </tr>
  <tr>
  </tr>
  </thead>
  <tbody>
  <%= render @machines %>
  </tbody>
</table>

app/views/admin/machines/new.html.erb
<%= modal_form_for @machine do |f| %>
  <div class="modal-header">
    <h4 class="modal-title text-center">New machine</h4>
  </div>
  <div class="modal-body">
    <%= render 'machine_fields', f: f %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <%= f.submit "Create machine", class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/machines/update.js.erb
var machine_row = $("<%= "#machine-#{@machine.id}" %>")
$('#forms-modal').modal('hide')
machine_row.replaceWith("<%= j render 'machine', machine: @machine %>");
$(machine_row.selector).addClass("info");